### ISSUE TITLE
Not work on HTC A9

### ISSUE THREAD

**Issue by Ketagalan** [Magisk-Modules-Repo/magisk-notosanscjk-nougat#10]
It doesn't work on HTC One A9 with 2.18.617.41 firmware. It still shows default Xin-Gothic font.

**Comment by simonsmh** [comment]
Please post your /etc/fonts.xml, thank you.

**Comment by Ketagalan** [comment]
https://drive.google.com/file/d/0B9a8-hsiexYTU0dtb3ZGYThJbk0/view?usp=drivesdk
Here it is, I also took it a look, there seems to be several customized sections by HTC, including Chinese (both SC and TC) and Emoji… I'll try to delete or change some texts later and report here!

**Comment by simonsmh** [comment]
Well... Would you please formate your cache? There is no problem dealing with the modified fonts.xml, I think.
BTW, please post the edited fonts.xml, thanks! It should be located at /magisk/notosanscjk-nougat/system/etc/fonts.xml .

**Comment by Ketagalan** [comment]
It's the fonts xml modified by me, I misunderstood that your mod doesn't work is caused by the new firmware or Magisk v14, so I uninstalled your mod and edited it directly which is under root/system/etc, and it works now. 😂
https://drive.google.com/file/d/0B9a8-hsiexYTNzFVNEc3dWxVcFU/view?usp=drivesdk

I just removed the modified sections by HTC. Btw what's the cache needing to be formatted you mentioned?

**Comment by Ketagalan** [comment]
Oh, if you mean the /cache, I had wiped it but didn't work… :(

**Comment by simonsmh** [comment]
I think you need to reinstall the module.
Then, please post /magisk/notosanscjk-nougat/system/etc/fonts.xml here, thank you.

**Comment by Ketagalan** [comment]
After reinstalling module, it works normally! The file under /root/magisk/notosanscjk-nougat/system/etc is the same as the first file I uploaded, and the one under root/system/etc is changed to a modified file by your module. Anyway, thank you very much!
