### ISSUE TITLE
安装这个模块会导致magisk损坏，所有模块不见，并且不能再安装。

### ISSUE THREAD

**Issue by cv0cv0** [Magisk-Modules-Repo/magisk-notosanscjk-nougat#11]
查看/magisk发现所有文件被清空。

**Comment by simonsmh** [comment]
暂时用 recovery 刷，在oreo上安装时有bug，sendfile return 2

**Comment by cv0cv0** [comment]
好像是magisk的bug，大文件都有这个问题，我自制了一个也是这样。

**Comment by simonsmh** [comment]
我不知道该怎么反馈这类问题，@topjohnwu 直接把issue页面关闭了，XDA上同样鱼龙混杂，很无奈。。

**Comment by cv0cv0** [comment]
对了，我是7.1.2，LineageOS-20171005版。

**Comment by simonsmh** [comment]
是5.3.5的MagiskManager么

**Comment by cv0cv0** [comment]
5.3.0、5.3.5，14.0、14.2都有这个问题。我用过你这个模块很长时间，后来重装系统就有这个问题了，重装之前也是14.0、5.3.5。刚出的时候自制过模块，遇到大文件拷贝不完整，后来你这个模块出了，竟然可以，我用的是单文件那个字体。

**Comment by cv0cv0** [comment]
好像只有我遇到这个问题了，没见别人反馈。

**Comment by simonsmh** [comment]
我自己就遇到了，迷
我这是这两天更新8.0才出现的情况

**Comment by cv0cv0** [comment]
好像更新没问题，重新安装就不行。我原来用的好好的，重装系统才遇到这个问题。

**Comment by simonsmh** [comment]
行，感谢反馈。

**Comment by cv0cv0** [comment]
有人装xposed也出现这个问题了。酷安有人出现这个问题，只是很多人感觉莫名其妙。

**Comment by cv0cv0** [comment]
现在用刷机包也用着。对了，8.0的fonts.xml要怎么修改？

**Comment by simonsmh** [comment]
看update-binary就行，方法通用的

**Comment by simonsmh** [comment]
在recovery刷目前来说是可以的，遇到问题就rec刷就好了

**Comment by cv0cv0** [comment]
rec刷一样。现在不是刷不进去，而是刷进去重启magisk就出问题了。

**Comment by cv0cv0** [comment]
据说8.0改了。我研究一下你的update-binary。以前看了一下，没看懂。

**Comment by cv0cv0** [comment]
我看你写的好像也没根据系统区分。

**Comment by simonsmh** [comment]
正则匹配，8.0没区别的
Rec 也刷不进去么，有点奇怪啊
不需要区分呀，7.0和8.0都一样可以用的

**Comment by cv0cv0** [comment]
能刷进去，但是重启会导致所有模块丢失，并不能再重新安装。

**Comment by cv0cv0** [comment]
新加了一段注释。

**Comment by simonsmh** [comment]
7.0和8.0都一样可以用的，我不是单纯文件替换完成的模块

**Comment by simonsmh** [comment]
我1.5.1版本更新到新template（1410，magisk 14.1+ β ），似乎现在没问题了？

**Comment by kkren** [comment]
在更新到magisk 14.5后好像没有问题了

**Comment by simonsmh** [comment]
@kkren 等magisk正式版更新，应用新模板后我会关闭这个issue
