### ISSUE TITLE
应用模块后，Aldiko book reader 调用系统字体，部分显示口口

### ISSUE THREAD

**Issue by easyinplay** [Magisk-Modules-Repo/magisk-notosanscjk-nougat#13]
不正常显示的有几类，英文（只有极少数）、数字、标点符号（小部分符合，如 “ 和 —— ）,我贴两张图一种是正常文本内容，一种是使用模块字体后的显示

![default](https://user-images.githubusercontent.com/4202001/32216699-95632e30-be60-11e7-8781-a2f800f09bc5.jpg)
![default](https://user-images.githubusercontent.com/4202001/32216715-a49b5f62-be60-11e7-8eae-c71582926edd.jpg)

**Comment by simonsmh** [comment]
咦，难道两种 `—` 不一样嘛

**Comment by simonsmh** [comment]
如果可能的话，还请附带设备信息，系统版本信息，Magisk版本信息，Magisk日志，此段文本和复现步骤。

**Comment by easyinplay** [comment]
一加3T ， 使用的rom是 AOSPA 7.3.0 ，安卓版本 7.1.2； Magisk 14.3，这个不需要magisk日志吧，乱码是在Aldiko book reader 中出现的，我贴一下乱码的epub文件，随便翻几页既可以发现（主要是部分英文和个别标点符号乱码）；复现步骤：按照该模块后，打开这个epub文件，即可看到。


[李笑来 - 把时间当作朋友运用心智获得解放.zip](https://github.com/Magisk-Modules-Repo/magisk-notosanscjk-nougat/files/1444815/-.zip)

**Comment by simonsmh** [comment]
我暂时移除了DroidSansFallback，更新后再试试看？
还有，强烈建议使用更加专业一些的软件，比如Moon+ Reader静读天下之类的软件尝试一下，个人认为阅读效果要好得多（

**Comment by easyinplay** [comment]
更新了去除DroidSansFallback之后的模块版本，结果————除了标点符号、数字和英文全部成豆腐块了（不过在某方面也印证了DroidSansFallback对Gbk编码的epub文档支持不完善的猜测），希望能够恢复DroidSansFallback（我暂时刷了之前的版本），谢谢  
哈哈 ～～
Moon+ Reader之前也用过，但是对某些epub的样式显示没有Aldiko显示出来好看（包括字体的粗细、样式排版）
不过Moon+ Reader整体上确实很优秀，希望朋友在之后的模块更新里面能够恢复DroidSansFallback，再次感谢朋友的耐心回复和工作

**Comment by simonsmh** [comment]
好的，我下午会revert的

**Comment by easyinplay** [comment]
十分感谢

**Comment by simonsmh** [comment]
我偏向于寻找一个符合你要求的DroidSansFallback.ttf，如果你找到了的话，欢迎随时pr或与我联系

**Comment by easyinplay** [comment]
还真让我找到了一个，在包里面替换掉 DroidSansFallback.ttf 之后，一切显示完美。
附上地址：
https://github.com/jenskutilek/free-fonts/blob/master/Droid/Droid%20Sans%20Fallback/DroidSansFallback.ttf

**Comment by simonsmh** [comment]
感谢，此问题已修复

**Comment by easyinplay** [comment]
试验了一下，和版本有关系，2.2以上的版本可以正常显示
附一个最新版：2.3.1 属于Godot Engine项目，字体应该是持续更新的，找不到更新的源头了
https://github.com/godotengine/godot/blob/master/thirdparty/fonts/DroidSansFallback.ttf

**Comment by simonsmh** [comment]
🆗
