### ISSUE TITLE
1.5.1版安装不上

### ISSUE THREAD

**Issue by KyonLi** [Magisk-Modules-Repo/magisk-notosanscjk-nougat#14]
Android 7.1.2
magisk版本: 14.0
magisk manager: 5.4.0
recovery: twrp-3.1.1
NotoSansCJK-1.5.1

magisk为全新安装

recovery下先是提示无法挂载/system，手动挂载后依然无法完成安装

![2017-11-07 09 22 45](https://user-images.githubusercontent.com/7446107/32472369-4e4906ea-c39d-11e7-84d7-71c296048af7.jpg)

![2017-11-07 09 22 56](https://user-images.githubusercontent.com/7446107/32472384-6369b128-c39d-11e7-95b6-8d9b37a6bcd4.jpg)

**Comment by simonsmh** [comment]
需要跟上游反馈，权限与挂载问题我修不了
你也可以试试看更新到 magisk 14.3

**Comment by KyonLi** [comment]
@simonsmh 谢谢回复，可是相同环境下1.5(65faa13)就可以安装

![2017-11-08 09 29 04](https://user-images.githubusercontent.com/7446107/32527040-4ff489b8-c467-11e7-8c5e-26850481cf88.jpg)

**Comment by simonsmh** [comment]
你要么换个梯子重新下载一下，我没改东西，没道理的

**Comment by simonsmh** [comment]
哦 我错了，这得用14.3安装，下午我revert一下
