### ISSUE TITLE
Wrong package structure for the zip on Magisk repo

### ISSUE THREAD

**Issue by PeterCxy** [Magisk-Modules-Repo/magisk-notosanscjk-nougat#2]
The zip of this module on Magisk repo has an extra outer directory `magisk-notosanscjk-nougat-master` which makes it impossible to install from Magisk Manager. Removing it and rezipping fixed this issue.

**Comment by simonsmh** [comment]
It should be fixed last week...

Peter Cai <notifications@github.com>于2017年2月27日周一 23:23写道：

**Comment by simonsmh** [comment]
#1

**Comment by PeterCxy** [comment]
No I just downloaded it from Magisk Manager three times today and the installation all failed.. Then I took a look at the downloaded package and found out why.

**Comment by simonsmh** [comment]
I'm really sorry but I still can't reproduce it for now. Would you please report it to Magisk Manager? Thanks.
