### ISSUE TITLE
Migrate to SuperOTC

### ISSUE THREAD

**Issue by tzhao11** [Magisk-Modules-Repo/magisk-notosanscjk-nougat#3]
According to [https://www.google.com/get/noto/help/cjk/](https://www.google.com/get/noto/help/cjk/),
> All 36 OTF files above are bundled into a single OTC file, NotoSansCJK.ttc. It takes about 10MB less disk space than 36 separate OTF files.

**Comment by simonsmh** [comment]
NotoSansCJK.ttc is larger than 100mb, which is larger than the limit of GitHub uploading.
